# Generated by Django 3.0.2 on 2020-01-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('CHK', 'Checking'), ('SVG', 'Savings'), ('CRE', 'Credit')], max_length=3)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='branches.Branch')),
            ],
        ),
    ]
